[config]
name = "projectName"
author = "unknow"
tags = ["edited"]
[data]
console_color_foreground = 31
console_color_background = 47
[conditions]
true = ["1 > 1"]
[actions]
C_0_s_2 = ["$C_0_s_2.toml"]
C_0_s_3 = ["$C_0_s_3.toml"]
C_0_s_4 = ["$C_0_s_4.toml"]
C_0_s_5 = ["$C_0_s_5.toml"]
restart = ["$index.toml"]
C_0_s_1 = ["$C_0_s_1.toml"]
[client]
page = "pages/index.toml"
frameSize_x = 100
frameSize_y = 15
up = 72
down = 80
ok = 13
zoom = 61
unzoom = 45
exit = 27
